### ISSUE TITLE
how sird work with routes file

### ISSUE THREAD

**Issue by lshoo** [getquill/play-quill-jdbc#1]
Hello，I want write the route in conf/routes, when I add "routes" file under /conf and write :
GET         /                      controllers.Application.index
in" routes" file, but this route is not effect, how to sird work with "routes" file?
Thanks!

Shifu

**Comment by gustavoamigo** [comment]
If you want to use the router file, just follow this example:
https://www.playframework.com/documentation/2.5.x/ScalaCompileTimeDependencyInjection#providing-a-router

I don't think you can mix Sird with `conf/routes` file, you have to choose one approach or the other. If you created a `conf/routes` file, you should have a access to the generated class `router.Routes`. Just replace `val router = Router.from` with `val router = new Routes(...)` in `AppLoader`.

I find it easier to use Sird with Compile Time Injection, but that might just be a matter of taste.

**Comment by lshoo** [comment]
Thanks！
