### ISSUE TITLE
Use more permissive license

### ISSUE THREAD

**Issue by likern** [getquill/play-quill-jdbc#6]
I want to modify this template to use with new Play 2.6 to work in my work project.
But Apache 2.0 license requires a lot of work to do. State every modifications in original files, redistribute unmodified files as Apache, etc. Even though it might happen source code will be heavily reworked.

Is it possible to use more permissive and simple license, for example MIT? Or http://www.wtfpl.net? 
I think it will simplify stuff a lot.

**Comment by gustavoamigo** [comment]
You're right. MIT license would work for you?

**Comment by likern** [comment]
Thanks. Yes, it will work.

**Comment by gustavoamigo** [comment]
Done
